### ISSUE TITLE
home icon cannot be display

### ISSUE THREAD

**Issue by linitfor** [jtlw99/vicefox#1]
Hi developer,

     I found the home icon cannot be display on the top of the bar.

![圖片](https://github.com/jtlw99/vicefox/assets/58168507/dbb74324-d521-4b49-8b7d-f160b0edee9d)

**Comment by jtlw99** [comment]
sorry bro but i cant access to my computer right now!

**Comment by linitfor** [comment]
when can you fix this issue ?

**Comment by linitfor** [comment]
Hey guy ~~

I have fixed all the issue and enhance some feature for you. 
For example:
1. the adding to support show the extend plugin. 
2. Tuning the url bar size.
3. Tuning the url bar input size.
4. Tuning the navbar, tabbar, .....
5. Resizing the round of the web.

Tuning too much and forget it ...  XD

By the way, I am one of support this theme original development. If you are looking the code inside, you can find my name from your original codebase. XD
The original developer seem lose communication. I am glade to see you to maintain for him. 


[chrome_fox17.zip](https://github.com/jtlw99/vicefox/files/12572062/chrome_fox17.zip)

**Comment by jtlw99** [comment]
iam so sorry but the home icon is hidden by default due to oneline tweak so it cant be displayed on the top bar!
